spring:
  datasource:
    url: jdbc:mysql://localhost:3306/benefitingfarmersshopping?characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  #进行邮箱各个参数的设置
  mail:
    #配置smtp服务主机地址
    host: smtp.qq.com
    #发送者邮箱
    username: 951294416@qq.com
    #配置密码,注意不是真正的密码，而是刚刚申请到的授权码
    password: waivvytmcztrbdhd
    #端口号465或587
    port: 587
    #默认的邮件编码为UTF-8
    default-encoding: UTF-8
    #其他参数
    properties:
      mail:
        #配置SSL 加密工厂
        smtp:
          ssl:
            #本地测试，先放开ssl
            enable: false
            required: false
          #开启debug模式，这样邮件发送过程的日志会在控制台打印出来，方便排查错误
        debug: true
#开启日志功能
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
#  type-aliases-package: com.gouggou.shardingtable.entity    # 实体类所在的位置
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句